#removing all the configurations here, so that config-consumer doesnot override its configurations and try running at 8191 instead of 8080.
#server:
  #port: 8191
#spring:
  #cloud:
    #config:
      #server:
        #git:
          #uri: https://github.com/krish/spring-cloud-config
          #search-paths:
           #- '*service'



